package com.aimprosoft.noormal.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.aimprosoft.noormal.servicebuilder.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.aimprosoft.noormal.servicebuilder.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Arsalan
 * @see Employee
 * @see com.aimprosoft.noormal.servicebuilder.model.impl.EmployeeImpl
 * @see com.aimprosoft.noormal.servicebuilder.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee.
     *
     * @return the employee ID of this employee
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee.
     *
     * @param employeeId the employee ID of this employee
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the name of this employee.
     *
     * @return the name of this employee
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this employee.
     *
     * @param name the name of this employee
     */
    public void setName(String name);

    /**
     * Returns the age of this employee.
     *
     * @return the age of this employee
     */
    public int getAge();

    /**
     * Sets the age of this employee.
     *
     * @param age the age of this employee
     */
    public void setAge(int age);

    /**
     * Returns the date of birth of this employee.
     *
     * @return the date of birth of this employee
     */
    public Date getDateOfBirth();

    /**
     * Sets the date of birth of this employee.
     *
     * @param dateOfBirth the date of birth of this employee
     */
    public void setDateOfBirth(Date dateOfBirth);

    /**
     * Returns the email of this employee.
     *
     * @return the email of this employee
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this employee.
     *
     * @param email the email of this employee
     */
    public void setEmail(String email);

    /**
     * Returns the department of this employee.
     *
     * @return the department of this employee
     */
    public long getDepartment();

    /**
     * Sets the department of this employee.
     *
     * @param department the department of this employee
     */
    public void setDepartment(long department);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.aimprosoft.noormal.servicebuilder.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.aimprosoft.noormal.servicebuilder.model.Employee> toCacheModel();

    @Override
    public com.aimprosoft.noormal.servicebuilder.model.Employee toEscapedModel();

    @Override
    public com.aimprosoft.noormal.servicebuilder.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
