export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_COUNT_OF_DEPARTMENTS_SUCCESS = 'GET_COUNT_OF_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_VALIDATION_ERROR = 'GET_VALIDATION_ERROR';
export const DEPARTMENT_SAVE_FORM = 'departmentSaveForm';